---
version: 1.0.3
slug: nginx_stream_proxy
name: NginxStreamProxy
description: NginxStreamProxy
url: https://github.com/grzonu/ha_addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  3389/tcp: null
startup: system
timeout: 20
